import CardSkeleton from "@/components/cards/CardSkeleton";
import Event from "@/components/Event";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Pagination from "@/components/Pagination";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import axios from "../api/axios";
import Link from "next/link";

function Berita() {
  const [berita, setBerita] = useState([]);

  // useEffect(() => {
  //   // setNavigation("berita");
  // }, []);

  useEffect(() => {
    getBerita(1);
  }, []);

  const getBerita = async (page) => {
    try {
      const response = await axios.get(`berita/all?page=${page}`);

      const data = response.data.data;
      // const totalPages = response.data.meta.totalPages;

      // setPagination({
      //   ...pagination,
      //   currentPage: page,
      //   totalPages,
      // });

      setBerita(data);
    } catch (err) {
      console.warn(err);
    }
  };

  const convertDate = (dateStr) => {
    const date = new Date(dateStr);

    const options = { day: "numeric", month: "long", year: "numeric" };
    const formattedDate = date.toLocaleDateString("id-ID", options);

    return formattedDate;
  };

  return (
    <>
      <Head>
        <title>solotechnopark.go.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head>
      <main>
        <Navbar />
        <section className="mt-36">
          <div className="container pt-10 pb-20">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 justify-center items-stretch">
              {berita.length > 0 ? (
                berita.map((data, i) => (
                  <Link href={`berita/${data.slug}`} target="_blank" key={i}>
                    <Event
                      key={i}
                      type={"berita"}
                      slug={data.slug}
                      title={data.title}
                      date={convertDate(data.createdAt)}
                      image={data.image}
                    />
                  </Link>
                ))
              ) : (
                <>
                  <CardSkeleton />
                  <CardSkeleton />
                  <CardSkeleton />
                  <CardSkeleton />
                </>
              )}
            </div>
            <div className="flex justify-center mt-10 lg:mt-20">
              {/* <Pagination
                totalPage={pagination.totalPages}
                currentPage={pagination.currentPage}
              /> */}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

export default Berita;
