import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import React, { useState } from "react";
import KawasanSTP from "@/images/gedung-stc.png";
import Image from "next/image";
import Card from "@/components/cards/Card";
import Button from "@/components/Button";
import { NextSeo } from "next-seo";
import axios from "../api/axios";

function Kontak() {
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState(404);
  const [buttonText, setButtonText] = useState("Kirim");
  const [dataKontak, setDataKontak] = useState({
    nama: "",
    email: "",
    judul: "",
    pesan: "",
  });

  const handlerSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setButtonText("Loading ...");

    if (!dataKontak.nama || !dataKontak.email) {
      alert("Mohon lengkapi input nama dan email.");
      setLoading(false);
      setButtonText("Kirim Ulang");
      return;
    }

    try {
      const response = await axios.post("pesan", dataKontak);

      if (response.status === 200) {
        setLoading(false);
        setButtonText("Data berhasil dikirim");
        setStatus(response.status);
      } else {
        setLoading(false);
        setButtonText("Terjadi kesalahan! Kirim Ulang");
      }
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <>
      {/* <Head>
        <title>solotechnopark.go.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head> */}

      <NextSeo
        title="Profil - Solo Technopark"
        description="Kawasan Inovatif dan Berdaya Saing International. Pusat Inovasi dan Vokasi yang Memadukan Unsur Pengembangan Iptek, Kebutuhan Pasar, Industri dan Bisnis Untuk Penguatan Daya Saing Daerah."
        canonical="https://solotechnopark.id/"
        openGraph={{
          url: "https://solotechnopark.id/",
          title: "Profil - solo technopark",
          description: "Kawasan Inovatif dan Berdaya Saing International.",
          images: [
            {
              url: "/favicon.png",
              width: 800,
              height: 600,
              alt: "Profile Solo Technopark",
            },
          ],
          site_name: "Solo Technopark",
        }}
      />

      <Navbar />

      <header className="mt-20 pt-16 bg-contact-patern">
        <div className="container lg:h-[85vh] pb-20 grid lg:grid-cols-12 gap-5 lg:gap-10 items-center">
          <div className="mx-auto flex flex-col justify-center items-start lg:col-span-5 text-white">
            <h1 className="capitalize head-1 my-5  leading-[3.5rem]">
              Informasi <br /> Kontak
            </h1>
          </div>
          <div className="flex justify-end items-center lg:col-span-7 ">
            <Image className="w-full mt-10" src={KawasanSTP} alt="flow" />
          </div>
        </div>
      </header>

      <main className="">
        <section>
          <div className="container py-20">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10 md:gap-20">
              <div>
                <Card className={"shadow-lg p-5 md:p-10 border"}>
                  <div className="header border-b ">
                    <h4 className="uppercase text-lg font-medium text-gray-600">
                      Hubungi kami
                    </h4>
                    <h2 className="capitalize head-2 my-5">
                      Tidak bisa menemukan{" "}
                      <strong className="text-primary-100">informasi </strong>
                      yang Anda cari?
                    </h2>
                  </div>
                  {status === 200 ? (
                    <h1 className="mt-10 head-4">
                      Pesan anda sudah kami terima! <br /> <br /> Terimakasih
                      atas aspirasi yang telah anda berikan, kami akan
                      meresponnya melalui email anda{" "}
                      <strong className="text-primary-100">
                        {dataKontak.email}
                      </strong>
                    </h1>
                  ) : (
                    <form>
                      <div className="my-5">
                        <label className="mb-2 block head-4">Nama</label>
                        <input
                          required
                          className="bg-slate-100 w-full outline-primary-100 block text-md py-3 px-4 rounded-full"
                          type="text"
                          placeholder="Masukkan nama lengkap di sini"
                          value={dataKontak.nama}
                          onChange={(e) =>
                            setDataKontak({
                              ...dataKontak,
                              nama: e.target.value,
                            })
                          }
                        />
                      </div>
                      <div className="my-5">
                        <label className="mb-2 block head-4">Email</label>
                        <input
                          required
                          className="bg-slate-100 w-full outline-primary-100 block text-md py-3 px-4 rounded-full"
                          type="email"
                          placeholder="Masukkan email di sini"
                          value={dataKontak.email}
                          onChange={(e) =>
                            setDataKontak({
                              ...dataKontak,
                              email: e.target.value,
                            })
                          }
                        />
                      </div>
                      <div className="my-5">
                        <label className="mb-2 block head-4">Judul</label>
                        <input
                          className="bg-slate-100 w-full outline-primary-100 block text-md py-3 px-4 rounded-full"
                          type="text"
                          placeholder="Tentang apa yang ingin Anda tanyakan"
                          value={dataKontak.judul}
                          onChange={(e) =>
                            setDataKontak({
                              ...dataKontak,
                              judul: e.target.value,
                            })
                          }
                        />
                      </div>
                      <div className="my-5">
                        <label className="mb-2 block head-4">Pesan</label>
                        <textarea
                          className="bg-slate-100 w-full h-60 outline-primary-100 block text-md py-3 px-4 rounded-lg"
                          placeholder="Masukkan pesan yang ingin Anda sampaikan di sini"
                          value={dataKontak.pesan}
                          onChange={(e) =>
                            setDataKontak({
                              ...dataKontak,
                              pesan: e.target.value,
                            })
                          }
                        />
                      </div>
                      <div
                        className={`${
                          loading
                            ? "focus:outline-none disabled:opacity-25"
                            : ""
                        }`}
                        onClick={handlerSubmit}
                      >
                        <Button
                          className={
                            "bg-primary-gradient-x-100 text-white w-full hover:opacity-50"
                          }
                        >
                          {buttonText}
                        </Button>
                      </div>
                    </form>
                  )}
                </Card>
              </div>
              <div className="md:my-16">
                <div className="header border-b ">
                  <h4 className="uppercase text-lg font-medium text-gray-600">
                    Hubungi kami
                  </h4>
                  <h2 className="capitalize head-2 my-5">
                    Butuh &nbsp;
                    <strong className="text-primary-100">bantuan</strong> ?
                    kunjungi kami
                  </h2>
                </div>
                <ul className="my-5">
                  <li className="flex justify-start items-start gap-10 my-5">
                    <div className="bg-slate-100 p-4 inline-block rounded-full">
                      <svg
                        width="16"
                        height="20"
                        viewBox="0 0 16 20"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M8 10C8.55 10 9.021 9.804 9.413 9.412C9.805 9.02 10.0007 8.54933 10 8C10 7.45 9.804 6.979 9.412 6.587C9.02 6.195 8.54933 5.99933 8 6C7.45 6 6.979 6.196 6.587 6.588C6.195 6.98 5.99933 7.45067 6 8C6 8.55 6.196 9.021 6.588 9.413C6.98 9.805 7.45067 10.0007 8 10ZM8 19.625C7.86667 19.625 7.73333 19.6 7.6 19.55C7.46667 19.5 7.35 19.4333 7.25 19.35C4.81667 17.2 3 15.204 1.8 13.362C0.6 11.52 0 9.79933 0 8.2C0 5.7 0.804333 3.70833 2.413 2.225C4.02167 0.741667 5.884 0 8 0C10.1167 0 11.9793 0.741667 13.588 2.225C15.1967 3.70833 16.0007 5.7 16 8.2C16 9.8 15.4 11.521 14.2 13.363C13 15.205 11.1833 17.2007 8.75 19.35C8.65 19.4333 8.53333 19.5 8.4 19.55C8.26667 19.6 8.13333 19.625 8 19.625Z"
                          fill="#FF5544"
                        />
                      </svg>
                    </div>
                    <div>
                      <h4 className="text-lg md:text-2xl font-bold">Lokasi</h4>
                      <p className="text-sm md:text-xl my-2 text-gray-600">
                        Jl. Ki Hajar Dewantara No. 19 Jebres, Kec. Jebres, Kota
                        Surakarta{" "}
                      </p>
                    </div>
                  </li>
                  <li className="flex justify-start items-start gap-10 my-5">
                    <div className="bg-slate-100 p-4 inline-block rounded-full">
                      <svg
                        width="24"
                        height="20"
                        viewBox="0 0 20 16"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M18 4L10 9L2 4V2L10 7L18 2M18 0H2C0.89 0 0 0.89 0 2V14C0 14.5304 0.210714 15.0391 0.585786 15.4142C0.960859 15.7893 1.46957 16 2 16H18C18.5304 16 19.0391 15.7893 19.4142 15.4142C19.7893 15.0391 20 14.5304 20 14V2C20 1.46957 19.7893 0.960859 19.4142 0.585786C19.0391 0.210714 18.5304 0 18 0Z"
                          fill="#FF5544"
                        />
                      </svg>
                    </div>
                    <div>
                      <h4 className="text-lg md:text-2xl font-bold">Email</h4>
                      <p className="text-sm md:text-xl my-2  text-gray-600">
                        info@solotechnopark.id
                      </p>
                    </div>
                  </li>
                  <li className="flex justify-start items-start gap-10 my-5">
                    <div className="bg-slate-100 p-4 inline-block rounded-full">
                      <svg
                        width="24"
                        height="24"
                        viewBox="0 0 16 16"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          fillRule="evenodd"
                          clipRule="evenodd"
                          d="M1.88547 0.51017C2.06045 0.335459 2.27055 0.199929 2.50187 0.11256C2.73318 0.025192 2.98043 -0.012019 3.22721 0.00339321C3.47399 0.0188054 3.71469 0.0864889 3.93333 0.201958C4.15198 0.317428 4.34359 0.478046 4.49547 0.67317L6.29047 2.97917C6.61947 3.40217 6.73547 3.95317 6.60547 4.47317L6.05847 6.66317C6.03019 6.7766 6.03172 6.89542 6.06291 7.00808C6.0941 7.12074 6.15389 7.22343 6.23647 7.30617L8.69347 9.76317C8.77631 9.84592 8.87916 9.90581 8.99202 9.93701C9.10488 9.9682 9.22389 9.96964 9.33747 9.94117L11.5265 9.39417C11.7831 9.33001 12.0509 9.32503 12.3098 9.3796C12.5686 9.43417 12.8116 9.54687 13.0205 9.70917L15.3265 11.5032C16.1555 12.1482 16.2315 13.3732 15.4895 14.1142L14.4555 15.1482C13.7155 15.8882 12.6095 16.2132 11.5785 15.8502C8.93965 14.9217 6.54374 13.411 4.56847 11.4302C2.58776 9.45519 1.07708 7.05963 0.148471 4.42117C-0.213529 3.39117 0.111471 2.28417 0.851471 1.54417L1.88547 0.51017Z"
                          fill="#FF5544"
                        />
                      </svg>
                    </div>
                    <div>
                      <h4 className="text-lg md:text-2xl font-bold">Telepon</h4>
                      <p className="text-sm md:text-xl my-2  text-gray-600">
                        (+62) 271 666 628
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="container pb-20">
            <div className="w-full bg-slate-50 rounded-xl overflow-hidden">
              <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3955.173350482129!2d110.8516778147767!3d-7.556069194550727!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7a16e2b5ffa643%3A0xa0bf36ec85b94dfb!2sSolo%20Techno%20Park!5e0!3m2!1sid!2sid!4v1678085198664!5m2!1sid!2sid"
                width="100%"
                height={450}
                style={{ border: 0 }}
                allowFullScreen
                loading="lazy"
                referrerPolicy="no-referrer-when-downgrade"
              />
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </>
  );
}

export default Kontak;
