// import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import ImageProfile from "@/images/Mas-Gibran.png";
import KawasanSTP from "@/images/Kawsan-STP-6.png";
import BaganWeb from "@/images/Bagan-Web-3-b.png";
import IconCheck from "@/images/check.svg";
import ImageSejarahSTP from "@/images/sejarah-stp-v2.png";
import Image from "next/image";
import Footer from "@/components/Footer";
import { NextSeo } from "next-seo";
import dataLeadership from "@/data/dataLeadership.json";
import dataProfilJSON from "@/data/dataProfil";

const dataDeskripsiProfil = {
  title: "Profil Solo Technopark",
  paragraph: [
    "Sebagai Unit Pelaksana Teknis Daerah (UPTD) pada BALITBANGDA Kota Surakarta, berdasarkan Peraturan Walikota No. 15 Tahun 2022",
    "Menerapkan Pola Tata Kelola Badan Layanan Umum Daerah (BLUD) berdasarkan Perwali Surakarta No. 38 Tahun 2022",
  ],
};

export default function Profile() {
  const dataProfil = JSON.parse(dataProfilJSON);

  return (
    <>
      <NextSeo
        title="Profil - Solo Technopark"
        description="Sebagai Unit Pelaksana Teknis Daerah (UPTD) pada BALITBANGDA Kota Surakarta, berdasarkan Peraturan Walikota No. 15 Tahun 2022. Menerapkan Pola Tata Kelola Badan Layanan Umum Daerah (BLUD) berdasarkan Perwali Surakarta No. 38 Tahun 2022."
        canonical="https://solotechnopark.id/"
        openGraph={{
          url: "https://solotechnopark.id/",
          title: "profil - solo technopark",
          description: "Kawasan Inovatif dan Berdaya Saing International.",
          images: [
            {
              url: "https://solotechnopark.id/wp-content/uploads/2022/11/Template-Website-3-1536x827.jpg",
              width: 800,
              height: 600,
              alt: "Profile Solo Technopark",
            },
          ],
          site_name: "profil - solotechnopark",
        }}
      />

      <Head>
        <title>solotechnopark.go.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head>
      <Navbar />

      <main className="mt-20">makan nasi goreng</main>
      <Footer />
    </>
  );
}
