// import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { NextSeo } from "next-seo";
import Button from "@/components/Button";
import Link from "next/link";
import MitraSingle from "@/components/swiper/MitraSingle";
import ImageHead1 from "@/images/layanan/ogsci/ogsci-atas-1.jpg";
import ImageHead2 from "@/images/layanan/ogsci/ogsci-atas-2.jpg";
import ImageBody1 from "@/images/layanan/ogsci/ogsci-bawah-1.jpg";
import ImageBody2 from "@/images/layanan/ogsci/ogsci-bawah-2.jpg";
import ImageBody3 from "@/images/layanan/ogsci/ogsci-bawah-3.jpg";
import ImageBody4 from "@/images/layanan/ogsci/ogsci-bawah-4.jpg";
import dataBenefitOGSC from "@/data/layanan/dataManfaatOGSCI.json";

// Import modul atau dependensi yang dibutuhkan
import Card from "@/components/cards/Card";
import Image from "next/image";
import axios from "../api/axios";
import { BsCheckCircleFill } from "react-icons/bs";
import ProfilInstruktur from "@/components/swiper/ProfilInstruktur";
import Testimonial from "@/components/Testimonial";

export default function LayananOGSCI({ mitra, berita, testimoni }) {
  console.log(dataBenefitOGSC);

  return (
    <>
      <NextSeo
        title="Profil - Solo Technopark"
        description="Sebagai Unit Pelaksana Teknis Daerah (UPTD) pada BALITBANGDA Kota Surakarta, berdasarkan Peraturan Walikota No. 15 Tahun 2022. Menerapkan Pola Tata Kelola Badan Layanan Umum Daerah (BLUD) berdasarkan Perwali Surakarta No. 38 Tahun 2022."
        canonical="https://solotechnopark.id/"
        openGraph={{
          url: "https://solotechnopark.id/",
          title: "profil - solo technopark",
          description: "Kawasan Inovatif dan Berdaya Saing International.",
          images: [
            {
              url: "/favicon.png",
              width: 800,
              height: 600,
              alt: "Profile Solo Technopark",
            },
          ],
          site_name: "profil - solotechnopark",
        }}
      />

      <Head>
        <title>solotechnopark.go.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head>
      <Navbar />

      <main className="mt-20">
        <section className="bg-flower-1">
          <div className="container">
            <div className="h-[90vh] flex flex-col justify-center">
              <h1 className="head-1 mb-5 max-w-3xl text-white">
                Oil & Gas Skill Center of Indonesia
              </h1>
              <Link
                href={
                  "https://docs.google.com/forms/d/e/1FAIpQLSe5n7zk-RG2-tESLGzcDKKwLimXKU5HAkLkphECLkqXhD4adw/viewform"
                }
                target="_blank"
              >
                <Button className="bg-blue-600 text-white hover:opacity-50 hover:bg-primary-gradient-200">
                  Pendaftaran
                </Button>
              </Link>
            </div>
          </div>
        </section>

        <section className="bg-gray-100">
          <div className="container py-5">
            <MitraSingle data={mitra} index={1} />
          </div>
        </section>

        <section className="">
          <div className="container pt-20">
            <h2 className="head-2 my-10 text-center max-w-3xl mx-auto">
              Apasih itu diklat Oil and Gas Skill Center of Indonesia?
            </h2>

            <div className="text-center max-w-5xl mx-auto text-gray-600">
              <p className="mb-4">
                Oil and Gas Skill Center of Indonesia (OGSCI) adalah sebuah
                program pelatihan yang diselenggarakan oleh Satuan Kerja Khusus
                Pelaksana Kegiatan Usaha Hulu Minyak dan Gas Bumi (SKK Migas)
                bekerja sama dengan Solo Technopark. Program ini bertujuan untuk
                memberikan fasilitas lengkap sebagai sarana sosialisasi,
                komunikasi, edukasi, dan informasi terkait industri hulu migas
                di Indonesia.
              </p>
              <p>
                Melalui pelatihan-pelatihan yang diselenggarakan di OGSCI,
                peserta akan mempelajari berbagai keterampilan dan teknik
                terkait industri hulu migas seperti electrical, instrument,
                mechanical, process operator, dan health and safety environment.
                Selain itu, program pelatihan OGSCI juga menawarkan pelatihan di
                bidang konstruksi dan manajemen proyek.
              </p>
            </div>
          </div>
        </section>

        <section className="">
          <div className="container py-20">
            <h2 className="head-2 my-10 text-center max-w-3xl mx-auto">
              Apa yang kita dapat pada diklat Oil and Gas Skill Center
              Indonesia?{" "}
            </h2>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 lg:gap-0">
              {dataBenefitOGSC &&
                dataBenefitOGSC.map((data, i) => (
                  <Card
                    key={i}
                    className={
                      "bg-gray-100 p-8 flex items-start gap-10 lg:mx-5 bg-rounded-2"
                    }
                  >
                    <div>
                      <h3
                        className="text-2xl font-bold text-primary-100 mt-5 lg:mt-0 mb-6"
                        style={{ maxWidth: "14rem" }}
                      >
                        {data.title}
                      </h3>
                      <p className="text-gray-600 max-w-md">{data.content}</p>
                    </div>
                  </Card>
                ))}
            </div>
          </div>
        </section>

        <section className="">
          <div className="container">
            <h2 className="head-2 my-10 text-center max-w-3xl mx-auto">
              Sertifikasi apa yang akan didapatkan di diklat ini?{" "}
            </h2>

            <div className="text-center max-w-5xl mx-auto text-gray-600">
              <p className="mb-4">
                Sertifikat yang diberikan dalam setiap pelatihan dari kami
                merupakan sertifikat yang diakui secara Nasional yakni melalui
                Badan Nasional Sertifikasi Profesi (BNSP) dan Kementrian Tenaga
                Kerja Republik Indonesia (Kemenaker) maupun Internasional oleh
                Engineering Construction Industry Training Board (ECITB) dan
                Offshore Petroleum Industry Training Organization (OPITO).
              </p>
            </div>
          </div>
        </section>

        {/* image galery */}
        <section className="">
          <div className="container py-20">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 lg:gap-10 mb-10">
              <div className="flex justify-center items-center bg-primary-gradient-x-100 rounded-3xl h-96 overflow-hidden">
                <Image
                  className="object-cover w-full h-full"
                  src={ImageHead1}
                  width={540}
                  height={400}
                  alt="image head"
                />
              </div>
              <div className="flex justify-center items-center bg-primary-gradient-x-100 rounded-3xl h-96 overflow-hidden">
                <Image
                  className="object-cover w-full h-full"
                  src={ImageHead2}
                  width={540}
                  height={400}
                  alt="image head"
                />
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 lg:gap-10">
              <div className="flex justify-center items-center bg-primary-gradient-x-100 rounded-3xl h-44 overflow-hidden">
                <Image
                  className="object-cover w-full h-full"
                  src={ImageBody1}
                  width={540}
                  height={400}
                  alt="image head"
                />
              </div>
              <div className="flex justify-center items-center bg-primary-gradient-x-100 rounded-3xl h-44 overflow-hidden">
                <Image
                  className="object-cover w-full h-full"
                  src={ImageBody2}
                  width={540}
                  height={400}
                  alt="image head"
                />
              </div>
              <div className="flex justify-center items-center bg-primary-gradient-x-100 rounded-3xl h-44 overflow-hidden">
                <Image
                  className="object-cover w-full h-full"
                  src={ImageBody3}
                  width={540}
                  height={400}
                  alt="image head"
                />
              </div>
              <div className="flex justify-center items-center bg-primary-gradient-x-100 rounded-3xl h-44 overflow-hidden">
                <Image
                  className="object-cover w-full h-full"
                  src={ImageBody4}
                  width={540}
                  height={400}
                  alt="image head"
                />
              </div>
            </div>
          </div>
        </section>

        {/* testimoni */}
        <section className="bg-gray-100 pt-10">
          <div className="container py-20">
            <div>
              <Testimonial data={testimoni} />
            </div>
          </div>
        </section>

        {/* call to action */}
        <section className="bg-primary-gradient-100">
          <div className="container py-20">
            <Card className="bg-white mx-10 lg:mx-24 p-20 flex flex-col justify-center items-center">
              <h2 className="head-2 text-primary-100 mx-auto text-center max-w-lg mb-10">
                Berminat mengikuti training OGSCI ?
              </h2>
              <p className="max-w-lg text-gray-600 mb-10 text-center">
                Klik tombol dibawah untuk mencari segala informasi yang terkait
                training oil and Gass Skill Center of Indonesia
              </p>
              <Link href={"/kontak"}>
                <Button className="bg-blue-600 text-white hover:opacity-50 hover:bg-primary-gradient-200">
                  Hubungi Kami
                </Button>
              </Link>
            </Card>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}

export async function getServerSideProps() {
  try {
    const mitraResponse = await axios.get("mitra");
    const testimoniResponse = await axios.get("testimonial");

    const mitra = mitraResponse.data.data;
    const testimoni = testimoniResponse.data.data;

    return {
      props: {
        mitra,
        testimoni,
      },
    };
  } catch (err) {
    console.warn(err);
    return {
      props: {
        mitra: [],
        berita: [],
        testimoni: [],
      },
    };
  }
}

const data = {
  rows: [
    {
      title: "Jenis Diklat yang Bisa Diikuti",
      content:
        '<ul><li><b>Diklat APBN:</b><span style="font-weight: 400"> Dibuka pada periode tertentu dan bebas biaya untuk seluruh warga indonesia</span></li><li><b>Diklat APBD:</b><span style="font-weight: 400"> Dibuka pada periode tertentu dan bebas biaya untuk yang memiliki KTP Surakarta</span></li><li><b>Diklat Mandiri:</b><span style="font-weight: 400"> Dibuka sepanjang tahun dan besaran biaya ditentukan sesuai dengan program yang diikuti </span></li></ul>',
    },
    {
      title: "Yang Dipelajari dalam Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Pelatihan hardskill sesuai dengan jurusan yang diambil</span></li><li><span style="font-weight: 400">Belajar menggunakan berbagai jenis mesin manufaktur</span></li><li><span style="font-weight: 400">Pelatihan softskill</span></li></ul>',
    },
    {
      title: "Penyaluran Kerja setelah Lulus Diklat",
      content:
        "Belum tentu. Penyaluran kerja menimbang aspek nilai akhir peserta diklat, usia peserta diklat, dan kebutuhan perusahaan mitra.",
    },
    {
      title: "Tahapan saat Mengikuti Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Tahap 1 merupakan pendidikan dasar teknik (Basic). Dalam tahapan basic ini,para siswa diajarkan ilmu dasar yang meliputi Lathe Work,Bench Work,Grinding Work,Milling Work, dan Gambar Teknik.</span></li><li><span style="font-weight: 400">Tahap 2 merupakan tahap lanjutan (Applied). Dalam tahapan lanjutan ( </span><i><span style="font-weight: 400">Applied </span></i><span style="font-weight: 400">), para siswa diajarkan ke tahap selanjutnya yakni seperti Otomasi Manufaktur, Desain Manufaktur, dan Mekanik Manufaktur.&nbsp;</span></li><li><span style="font-weight: 400">Tahap 3 merupakan tahap akhir (Advance).&nbsp; Peserta yang berhasil lulus berhak mendapatkan Sertifikat Keahlian yang dikeluarkan oleh Solotechnopark.</span></li></ul>',
    },
    {
      title: "Durasi Pelaksanaan Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Secara umum diklat dilaksanakan minimal 6 bulan hingga tahap applied dan maksimal 9 bulan hingga tahap advanced</span></li><li><span style="font-weight: 400">Apabila peserta mengikuti melalui program pemerintah maka durasi diklat didasarkan sesuai dengan kebijakan pemerintah</span></li></ul>',
    },
    {
      title: "Batas Usia untuk Mengikuti Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Tidak ada batasan usia</span></li><li><span style="font-weight: 400">Apabila ingin langsung mendapat rekomendasi penyaluran kerja minimal berusia 22 tahun</span></li></ul>',
    },
    {
      title: "Persyaratan untuk Mengikuti Diklat",
      content: "Minimal memiliki ijazah SLTA dan sederajat",
    },
    {
      title: "Persyaratan Fisik untuk Mengikuti Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Tidak buta warna</span></li><li><span style="font-weight: 400">Bukan penderita ayan/epilepsi</span></li></ul>',
    },
    {
      title: "Dokumen yang Harus Dipersiapkan",
      content:
        '<ul><li><span style="font-weight: 400">Fotocopy KTP Calon Peserta</span></li><li><span style="font-weight: 400">Fotocopy KTP Orangtua</span></li><li><span style="font-weight: 400">Fotocopy KK</span></li><li><span style="font-weight: 400">Fotocopy Ijasah</span></li><li><span style="font-weight: 400">Fotocopy Transkrip Nilai</span></li><li><span style="font-weight: 400">Surat Keterangan Sehat</span></li><li><span style="font-weight: 400">Surat Pernyataan (Bermaterai) * Didapat saat registrasi offline</span></li><li><span style="font-weight: 400">SKCK</span></li><li><span style="font-weight: 400">Pas Foto 4X6</span></li></ul>',
    },
    {
      title: "Minimal Nilai Ijazah untuk Mendaftar Diklat",
      content: "Tidak ada",
    },
    {
      title: "Penggunaan Materai pada Dokumen Diklat",
      content:
        "Ya, pada dokumen Surat Penyataan *Didapat saat registrasi offline",
    },
    {
      title: "Alur Pendaftaran Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Datang ke Pendaftaran STP</span></li><li><span style="font-weight: 400">Scan QR Code di Ruang Pendaftaran</span></li><li><span style="font-weight: 400">Mengisi Formulir Biodata Offline</span></li><li><span style="font-weight: 400">Melengkapi Berkas Persyaratan</span></li><li><span style="font-weight: 400">Tes Tulis</span></li><li><span style="font-weight: 400">Tes Wawancara</span></li></ul>',
    },
    {
      title: "Mendaftar untuk Banyak Jurusan Diklat",
      content: "Tidak bisa",
    },
    {
      title: "Warga di Luar Kota Surakarta Mengikuti Diklat",
      content: "Bisa",
    },
    {
      title: "Kuota Peserta Diklat",
      content:
        "Ada. Jumlahnya ditentukan tergantung program dan kebijakan Solo Technopark",
    },
    {
      title: "Biaya Pendaftaran Diklat",
      content:
        '<ul><li><span style="font-weight: 400">Bervariasi tergantung program</span></li><li><span style="font-weight: 400">Untuk lebih detail harap hubungi CP</span></li></ul>',
    },
  ],
};
