// import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { NextSeo } from "next-seo";
import Button from "@/components/Button";
import Link from "next/link";
import MitraSingle from "@/components/swiper/MitraSingle";
import dataPendukung from "../../data/layanan/dataPendukung.json";
import IconPendukung from "@/images/layanan/layanan-pendukung-icon.png";

// Import modul atau dependensi yang dibutuhkan
import axios from "axios";
import Card from "@/components/cards/Card";
import Image from "next/image";

export async function getServerSideProps() {
  try {
    const mitraResponse = await axios.get("mitra");
    const mitra = mitraResponse.data.data;

    return {
      props: {
        mitra,
      },
    };
  } catch (err) {
    console.warn(err);
    return {
      props: {
        mitra: [],
      },
    };
  }
}

export default function LayananPendukung({ mitra }) {
  return (
    <>
      <NextSeo
        title="Profil - Solo Technopark"
        description="Sebagai Unit Pelaksana Teknis Daerah (UPTD) pada BALITBANGDA Kota Surakarta, berdasarkan Peraturan Walikota No. 15 Tahun 2022. Menerapkan Pola Tata Kelola Badan Layanan Umum Daerah (BLUD) berdasarkan Perwali Surakarta No. 38 Tahun 2022."
        canonical="https://solotechnopark.id/"
        openGraph={{
          url: "https://solotechnopark.id/",
          title: "profil - solo technopark",
          description: "Kawasan Inovatif dan Berdaya Saing International.",
          images: [
            {
              url: "https://solotechnopark.id/wp-content/uploads/2022/11/Template-Website-3-1536x827.jpg",
              width: 800,
              height: 600,
              alt: "Profile Solo Technopark",
            },
          ],
          site_name: "profil - solotechnopark",
        }}
      />

      <Head>
        <title>solotechnopark.go.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://solotechnopark.id/wp-content/uploads/2021/09/Solo-Tecno.png"
        />
      </Head>
      <Navbar />

      <main className="mt-20">
        <section className="bg-primary-gradient-100">
          <div className="container">
            <div className="h-[90vh] flex flex-col justify-center">
              <h1 className="head-1 mb-5 max-w-3xl text-white">
                Layanan Pendukung di Kawasan Sains dan Teknologi Solo Technopark
              </h1>
              <Link href={"/kontak"}>
                <Button className="bg-blue-600 text-white hover:opacity-50 hover:bg-primary-gradient-200">
                  Hubungi Kami
                </Button>
              </Link>
            </div>
          </div>
        </section>

        <section className="bg-gray-100">
          <div className="container py-5">
            <MitraSingle data={mitra} index={1} />
          </div>
        </section>

        <section className="">
          <div className="container py-20">
            <h2 className="head-2 mb-5 text-center max-w-3xl mx-auto">
              Layanan Pendukung Kami
            </h2>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-5 lg:gap-0">
              {dataPendukung &&
                dataPendukung.map((data, i) => (
                  <Card
                    key={i}
                    className={
                      "bg-gray-100 p-8 flex items-start gap-10 lg:mx-5"
                    }
                  >
                    <Image
                      src={IconPendukung}
                      width={140}
                      height={140}
                      alt="icon"
                    />

                    <div>
                      <h3 className="head-4 text-primary-100 mt-5 lg:mt-0 mb-5">
                        {data.title}
                      </h3>
                      <p className="text-gray-600 ">{data.desc}</p>
                    </div>
                  </Card>
                ))}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
